version: "3.8"

services:
  # 1. DATABASE
  my-db:
    image: mysql:8.0
    container_name: p1-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project1_db
    ports:
      - "3307:3306" # Đã sửa để tránh cổng 3306
    volumes:
      - db_data:/var/lib/mysql

  # 2. BACKEND
  backend:
    build: ./backend
    container_name: p1-backend
    ports:
      # Đổi 8000 thành 8001 (Nếu 8000 bị lỗi)
      - "8001:80"
    depends_on:
      - my-db

  # 3. FRONTEND
  frontend:
    build: ./frontend
    container_name: p1-frontend
    ports:
      # Đổi 8080 thành 8081 (Nếu 8080 bị lỗi)
      - "8081:80"

volumes:
  db_data:
