version: "3.8"

services:
  # 1. DATABASE (MySQL)
  my-db:
    image: mysql:8.0
    container_name: p1-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # Mật khẩu root
      MYSQL_DATABASE: project1_db # Tên database tự tạo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Lưu dữ liệu để không mất khi tắt Docker

  # 2. BACKEND (PHP + PDO)
  backend:
    build: ./backend
    container_name: p1-backend
    ports:
      - "8000:80" # Truy cập API qua localhost:8000
    depends_on:
      - my-db

  # 3. FRONTEND (HTML)
  frontend:
    build: ./frontend
    container_name: p1-frontend
    ports:
      - "8080:80" # Truy cập Web qua localhost:8080

# Khai báo volume
volumes:
  db_data:
